### ISSUE TITLE
python-networkmanager uninstallable

### ISSUE THREAD

**Issue by andrewdhastings** [OpenAgInitiative/python-wifi-connect#19]
I know this is not directly related to your code as you don't maintain the python-networkmanger library, bit I can't seem to get this library to install on any OS/version that I have tried. 

Do you have any ideas. I would love to use this raw python version on my balena devices, but without this library, this whole concept is broken..

Any ideas?

Collecting dbus-python
[wifi-connect]    Downloading dbus-python-1.3.2.tar.gz (605 kB)
[wifi-connect]       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 605.5/605.5 kB 55.8 MB/s eta 0:00:00
[wifi-connect]    Installing build dependencies: started
[wifi-connect]    Installing build dependencies: finished with status 'error'
[wifi-connect]    error: subprocess-exited-with-error
[wifi-connect]    × pip subprocess to install build dependencies did not run successfully.
[wifi-connect]    │ exit code: 1
[wifi-connect]    ╰─> [78 lines of output]
[wifi-connect]        Collecting meson-python>=0.8.1
[wifi-connect]          Downloading meson_python-0.12.0-py3-none-any.whl (66 kB)
[wifi-connect]             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.2/66.2 kB 17.4 MB/s eta 0:00:00
[wifi-connect]        Collecting meson>=0.60.0
[wifi-connect]          Downloading meson-1.0.0-py3-none-any.whl (900 kB)
[wifi-connect]             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 900.3/900.3 kB 78.9 MB/s eta 0:00:00
[wifi-connect]        Collecting ninja
[wifi-connect]          Downloading ninja-1.11.1.tar.gz (27 kB)
[wifi-connect]          Installing build dependencies: started
[wifi-connect]          Installing build dependencies: finished with status 'done'
[wifi-connect]          Getting requirements to build wheel: started
[wifi-connect]          Getting requirements to build wheel: finished with status 'done'
[wifi-connect]          Preparing metadata (pyproject.toml): started
[wifi-connect]          Preparing metadata (pyproject.toml): finished with status 'done'
[wifi-connect]        Collecting patchelf
[wifi-connect]          Downloading patchelf-0.17.2.0.tar.gz (167 kB)
[wifi-connect]             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 60.5 MB/s eta 0:00:00
[wifi-connect]          Installing build dependencies: started
[wifi-connect]          Installing build dependencies: finished with status 'done'
[wifi-connect]          Getting requirements to build wheel: started
[wifi-connect]          Getting requirements to build wheel: finished with status 'done'
[wifi-connect]          Preparing metadata (pyproject.toml): started
[wifi-connect]          Preparing metadata (pyproject.toml): finished with status 'done'
[wifi-connect]        Collecting setuptools
[wifi-connect]          Using cached setuptools-65.7.0-py3-none-any.whl (1.2 MB)
[wifi-connect]        Collecting wheel
[wifi-connect]          Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
[wifi-connect]        Collecting pyproject-metadata>=0.6.1
[wifi-connect]          Downloading pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
[wifi-connect]        Collecting tomli>=1.0.0
[wifi-connect]          Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
[wifi-connect]        Collecting typing-extensions>=3.7.4
[wifi-connect]          Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
[wifi-connect]        Collecting packaging>=19.0
[wifi-connect]          Using cached packaging-23.0-py3-none-any.whl (42 kB)
[wifi-connect]        Building wheels for collected packages: ninja, patchelf
[wifi-connect]          Building wheel for ninja (pyproject.toml): started
[wifi-connect]          Building wheel for ninja (pyproject.toml): finished with status 'error'
[wifi-connect]          error: subprocess-exited-with-error
[wifi-connect]          × Building wheel for ninja (pyproject.toml) did not run successfully.
[wifi-connect]          │ exit code: 1
[wifi-connect]          ╰─> [9 lines of output]
[wifi-connect]              Traceback (most recent call last):
[wifi-connect]                File "/tmp/pip-build-env-iy8dpem9/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 612, in setup
[wifi-connect]                  cmkr = cmaker.CMaker(cmake_executable)
[wifi-connect]                File "/tmp/pip-build-env-iy8dpem9/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 149, in __init__
[wifi-connect]                  self.cmake_version = get_cmake_version(self.cmake_executable)
[wifi-connect]                File "/tmp/pip-build-env-iy8dpem9/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 104, in get_cmake_version
[wifi-connect]                  raise SKBuildError(
[wifi-connect]              Problem with the CMake installation, aborting build. CMake executable is cmake
[wifi-connect]              [end of output]
[wifi-connect]          note: This error originates from a subprocess, and is likely not a problem with pip.
[wifi-connect]          ERROR: Failed building wheel for ninja
[wifi-connect]          Building wheel for patchelf (pyproject.toml): started
[wifi-connect]          Building wheel for patchelf (pyproject.toml): finished with status 'error'
[wifi-connect]          error: subprocess-exited-with-error
[wifi-connect]          × Building wheel for patchelf (pyproject.toml) did not run successfully.
[wifi-connect]          │ exit code: 1
[wifi-connect]          ╰─> [9 lines of output]
[wifi-connect]              Traceback (most recent call last):
[wifi-connect]                File "/tmp/pip-build-env-x6dr3bpm/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 612, in setup
[wifi-connect]                  cmkr = cmaker.CMaker(cmake_executable)
[wifi-connect]                File "/tmp/pip-build-env-x6dr3bpm/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 149, in __init__
[wifi-connect]                  self.cmake_version = get_cmake_version(self.cmake_executable)
[wifi-connect]                File "/tmp/pip-build-env-x6dr3bpm/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 104, in get_cmake_version
[wifi-connect]                  raise SKBuildError(
[wifi-connect]              Problem with the CMake installation, aborting build. CMake executable is cmake
[wifi-connect]              [end of output]
[wifi-connect]          note: This error originates from a subprocess, and is likely not a problem with pip.
[wifi-connect]          ERROR: Failed building wheel for patchelf
[wifi-connect]        Failed to build ninja patchelf
[wifi-connect]        ERROR: Could not build wheels for ninja, patchelf, which is required to install pyproject.toml-based projects
[wifi-connect]        [end of output]
[wifi-connect]    note: This error originates from a subprocess, and is likely not a problem with pip.
[wifi-connect]
[wifi-connect]  error: subprocess-exited-with-error
[wifi-connect]  × pip subprocess to install build dependencies did not run successfully.
[wifi-connect]  │ exit code: 1
[wifi-connect]  ╰─> See above for output.
[wifi-connect]  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by falkyre** [comment]
Try updating your pip3 to the latest version.  I installed this on Raspian Bullseye running Python 3.9 with pip 23.2.1 without issue.

**Comment by falkyre** [comment]
If you come across this, the python-networkmanager is broken under the latest Raspberry Pi OS Bookworm.  It just does not work at all.

**Comment by polymerchm** [comment]
I am using the python-sdbus-networkmanager.    Works well.   A bit of a learning curve.    Will be putting up a forked version of this repo based on that.
